import type { MemorySourceActionManifest } from 'dsh-mnemon/contracts'
const identity = { id: { type: 'string', maxLength: 100 }, version: { type: 'integer', minimum: 1 } }
const invocation = { ...identity, variables: { type: 'object' }, count: { type: 'integer', minimum: 0, maximum: 1000 }, interval: { type: 'integer', minimum: 0, maximum: 1000 }, startAfter: { type: 'integer', minimum: 1, maximum: 1000 } }
const fields = { title: { type: 'string', minLength: 1, maxLength: 300 }, content: { type: 'string', minLength: 1, maxLength: 30000 }, scope: { type: 'string', enum: ['project', 'global'] }, data: { type: 'object', additionalProperties: false, properties: { category: { type: 'string', maxLength: 100 }, summary: { type: 'string', maxLength: 500 }, tags: { type: 'string', maxLength: 1000 }, enabled: { type: 'boolean' } } } }
export const promptActions: MemorySourceActionManifest[] = [
  { operation: {"effects":["append"],"execution":"immediate"} satisfies import('dsh-mnemon/contracts').MemoryOperationSemantics, id: 'create-prompt', description: 'Create the exact displayed reusable prompt after explicit instruction-library approval. Skills remain proposals until separately approved.', capability: 'write', authority: 'instruction-update', inputSchema: { type: 'object', additionalProperties: false, required: ['title', 'content'], properties: fields } },
  { operation: {"effects":["update"],"execution":"immediate","requiresReadGrant":true} satisfies import('dsh-mnemon/contracts').MemoryOperationSemantics, id: 'update-prompt', description: 'Update this exact prompt version after explicit instruction-library approval. Read its content and version before proposing a change.', capability: 'write', authority: 'instruction-update', inputSchema: { type: 'object', additionalProperties: false, required: ['id', 'version'], properties: { ...identity, ...fields } } },
  { operation: {"effects":["coordinate"],"execution":"immediate","requiresReadGrant":true} satisfies import('dsh-mnemon/contracts').MemoryOperationSemantics, id: 'schedule-prompt', description: 'Schedule an approved prompt in this session after explicit approval. Count zero repeats until stopped; interval zero means one use. Variables are literal data.', capability: 'write', authority: 'session-instructions', inputSchema: { type: 'object', additionalProperties: false, required: ['id', 'version'], properties: invocation } },
  { operation: {"effects":["coordinate"],"execution":"immediate","requiresReadGrant":true} satisfies import('dsh-mnemon/contracts').MemoryOperationSemantics, id: 'use-prompt', description: 'Use this approved prompt once. Explicit wake continues the running session at its next step, or wakes an idle conversation. Read the exact version first.', capability: 'write', authority: 'session-instructions', inputSchema: { type: 'object', additionalProperties: false, required: ['id', 'version'], properties: { ...identity, variables: { type: 'object' }, wake: { type: 'boolean' } } } },
  { operation: {"effects":["coordinate"],"execution":"immediate","requiresReadGrant":true} satisfies import('dsh-mnemon/contracts').MemoryOperationSemantics, id: 'stop-prompt', description: 'Stop the exact session schedule version. A stopped schedule remains in history.', capability: 'write', authority: 'session-instructions', inputSchema: { type: 'object', additionalProperties: false, required: ['id', 'version'], properties: identity } },
]
export const promptOperation = { 'create-prompt': 'create', 'update-prompt': 'update', 'schedule-prompt': 'schedule', 'use-prompt': 'use-now', 'stop-prompt': 'stop-schedule' } as const
