export const DEFAULT_IDLE_REVIEW_MS = 30_000
export const DEFAULT_RUNTIME_MEMORY_LIMIT_BYTES = 10 * 1024
export const DEFAULT_RUNTIME_USER_LIMIT_BYTES = 4 * 1024
export const MAX_RUNTIME_MEMORY_LIMIT_BYTES = 1024 * 1024
export const DEFAULT_RUNTIME_MAINTENANCE_MAX_TOKENS = 8_192
export const MAX_RUNTIME_MAINTENANCE_MAX_TOKENS = 1_000_000
export { DEFAULT_EMBEDDING_ENDPOINT, DEFAULT_EMBEDDING_MODEL, DEFAULT_EMBEDDING_PROTOCOL, MNEMON_EMBEDDING_PROTOCOLS } from "./protocol.ts"

export const DEFAULT_TIMEOUT_MS = 10_000
export const DEFAULT_RECALL_LIMIT = 10
export const DEFAULT_RECALL_QUALITY_POLICY = 'strict-v1'
export const DEFAULT_RECALL_LOW_SCORE_THRESHOLD = 0.25
export const DEFAULT_RECALL_HIGH_SCORE_THRESHOLD = 0.6
export const DEFAULT_RECALL_CANDIDATE_MULTIPLIER = 3
export const DEFAULT_RECALL_MAX_MEDIUM_RESULTS = 4
export const DEFAULT_RECALL_MAX_UNKNOWN_RESULTS = 2
