import type { ReactNode } from 'react'

/** CSS declarations for custom plugin layouts, scoped to their own root. */
export const memoryPluginTokens = `--mc-text:var(--dsw-alias-label-primary,CanvasText);--mc-muted:var(--dsw-alias-label-secondary,GrayText);--mc-faint:var(--dsw-alias-label-tertiary,GrayText);--mc-border:var(--dsw-alias-border-l2,color-mix(in srgb,CanvasText 15%,Canvas));--mc-surface:var(--dsw-alias-bg-layer-3,Canvas);--mc-input:var(--dsw-alias-bg-layer-2,Canvas);--mc-base:var(--dsw-alias-bg-base,Canvas);--mc-hover:var(--dsw-alias-interactive-bg-hover,color-mix(in srgb,CanvasText 7%,Canvas));--mc-error:var(--dsw-alias-state-error-primary,CanvasText);--mc-focus:var(--dsw-alias-brand-primary,CanvasText);`

/** Shared optional-plugin surfaces use the host's semantic colors in both themes. */
export const memoryPluginStyles = `
[data-mnemon-collection]{${memoryPluginTokens}color:var(--mc-text);min-width:0;padding:4px 0 24px;font-size:13px;line-height:1.55;container-type:inline-size}
[data-mnemon-collection] *,[data-mnemon-collection] *:before,[data-mnemon-collection] *:after{box-sizing:border-box}
[data-mnemon-collection] header{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}[data-mnemon-collection] header>div{min-width:0}[data-mnemon-collection] h2{font-size:16px;font-weight:500;line-height:24px;margin:0 0 6px}[data-mnemon-collection] h3{font-size:14px;font-weight:500;margin:0}[data-mnemon-collection] p{line-height:1.65;margin:8px 0;overflow-wrap:anywhere}[data-mnemon-collection] small{color:var(--mc-faint);font-size:12px}
[data-mnemon-collection] button,[data-mnemon-collection] select,[data-mnemon-collection] input,[data-mnemon-collection] textarea{font:inherit;color:var(--mc-text);border:1px solid var(--mc-border);border-radius:9px;background:var(--mc-input);padding:7px 10px;max-width:100%;min-height:34px}[data-mnemon-collection] select option{color:var(--mc-text);background:var(--mc-input)}[data-mnemon-collection] button{cursor:pointer;white-space:normal;overflow-wrap:anywhere;background:transparent;transition:background .12s}[data-mnemon-collection] button:hover:not(:disabled){background:var(--mc-hover)}[data-mnemon-collection] button:disabled{opacity:.45;cursor:default}[data-mnemon-collection] button[data-primary=true]{background:var(--mc-text);color:var(--mc-surface);border-color:var(--mc-text)}[data-mnemon-collection] button[data-primary=true]:hover:not(:disabled){background:color-mix(in srgb,var(--mc-text) 85%,var(--mc-surface))}[data-mnemon-collection] :is(button,input,textarea,select,summary,a):focus-visible{outline:2px solid var(--dsw-alias-brand-primary,var(--mc-text));outline-offset:3px}[data-mnemon-collection] input[type=checkbox]{width:16px;min-height:16px;height:16px;accent-color:var(--mc-text)}[data-mnemon-collection] textarea{resize:vertical;min-height:80px}
[data-mnemon-collection] .mc-toolbar{display:flex;gap:4px;flex-wrap:wrap;margin:18px 0;padding-bottom:12px;border-bottom:1px solid var(--mc-border)}[data-mnemon-collection] .mc-toolbar input{flex:1;min-width:150px;margin-left:8px}[data-mnemon-collection] .mc-toolbar button{border-color:transparent;color:var(--mc-muted)}[data-mnemon-collection] .mc-toolbar button[aria-pressed=true]{color:var(--mc-text);background:var(--mc-hover);font-weight:500}
[data-mnemon-collection] .mc-list{display:grid;gap:10px}[data-mnemon-collection] article{border:1px solid var(--mc-border);border-radius:12px;padding:16px;background:transparent;min-width:0}[data-mnemon-collection] .mc-content{white-space:pre-wrap;overflow-wrap:anywhere}[data-mnemon-collection] .mc-meta{display:flex;gap:7px;flex-wrap:wrap;align-items:center;margin:8px 0;font-size:12px;color:var(--mc-muted)}[data-mnemon-collection] .mc-badge{padding:2px 7px;border-radius:5px;background:var(--mc-hover);max-width:100%;overflow-wrap:anywhere}[data-mnemon-collection] footer{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}[data-mnemon-collection] details{margin-top:12px}[data-mnemon-collection] summary{cursor:pointer;color:var(--mc-muted)}[data-mnemon-collection] details>div{padding:8px 0;border-top:1px solid var(--mc-border)}
[data-mnemon-collection] form{border:1px solid var(--mc-border);border-radius:12px;padding:18px;margin:16px 0;background:var(--mc-surface)}[data-mnemon-collection] label{display:flex;min-width:0;flex-direction:column;gap:6px;margin-bottom:14px;color:var(--mc-muted);font-size:12px}[data-mnemon-collection] label input,[data-mnemon-collection] label textarea{width:100%}[data-mnemon-collection] label input[type=checkbox]{width:16px;align-self:flex-start}[data-mnemon-collection] .mc-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 16px}[data-mnemon-collection] [role=alert]{border:1px solid var(--dsw-alias-state-error-primary,var(--mc-border));border-radius:9px;padding:10px 12px;color:var(--dsw-alias-state-error-primary,var(--mc-text));background:var(--mc-surface)}[data-mnemon-collection] [role=status]{border:1px solid var(--mc-border);border-radius:9px;padding:10px 12px;color:var(--mc-text);background:var(--mc-hover)}[data-mnemon-collection] .mc-empty{padding:28px 16px;text-align:center;color:var(--mc-faint)}[data-mnemon-collection] .mc-metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(110px,1fr));gap:8px;margin:16px 0}[data-mnemon-collection] .mc-metrics>div{padding:12px;border:1px solid var(--mc-border);border-radius:10px}[data-mnemon-collection] .mc-metrics strong{display:block;font-size:20px;font-weight:500}[data-mnemon-collection] .mc-metrics span{font-size:12px;color:var(--mc-muted)}
[data-mnemon-collection] .mc-selection{display:flex;flex-direction:row;align-items:center;flex-wrap:wrap;gap:8px;margin:8px 0 14px;font-size:12px;color:var(--mc-muted)}[data-mnemon-collection] .mc-selection input[type=checkbox]{align-self:auto;margin:0}
@container(max-width:600px){[data-mnemon-collection] header{flex-wrap:wrap}[data-mnemon-collection] .mc-fields{grid-template-columns:1fr}[data-mnemon-collection] form{padding:14px}[data-mnemon-collection] .mc-toolbar button{padding:6px 8px}[data-mnemon-collection] .mc-toolbar input{flex-basis:100%;margin:6px 0 0}}@media(prefers-reduced-motion:reduce){[data-mnemon-collection] button{transition:none}}
`

export function MemoryPluginSurface(props: { title: string; description?: string; actions?: ReactNode; children: ReactNode }) {
  return <section data-mnemon-collection aria-label={props.title}><style>{memoryPluginStyles}</style><header><div><h2>{props.title}</h2>{props.description && <p>{props.description}</p>}</div>{props.actions && <div>{props.actions}</div>}</header>{props.children}</section>
}
export function MemoryPluginMetrics(props: { items: ReadonlyArray<{ label: string; value: string | number }> }) {
  return <div className="mc-metrics">{props.items.map(item => <div key={item.label}><strong>{item.value}</strong><span>{item.label}</span></div>)}</div>
}
export function MemoryPluginNotice(props: { error?: boolean; children: ReactNode }) {
  return <p role={props.error ? 'alert' : 'status'}>{props.children}</p>
}
